# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('Cognome', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Autore',
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('Descrizione', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Genere',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, null=True)),
                ('Data', models.DateField(null=True)),
                ('Data_acquisto', models.DateField(null=True)),
                ('autore', models.ManyToManyField(to='libreria.Autore')),
                ('genere', models.ManyToManyField(to='libreria.Genere')),
            ],
            options={
                'verbose_name_plural': 'Libro',
            },
        ),
    ]
