# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Data pubblicazione',
            new_name='Data',
        ),
    ]
