# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20181029_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Data acquisto',
            field=models.DateField(null=True),
        ),
    ]
