# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_libro_data acquisto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Data acquisto',
            new_name='Data_acquisto',
        ),
    ]
